// @flow

export const ErrorCode = {
    ENQUIRY_TIMEOUT: 'SYSERR_00001',
    UPDATE_TIMEOUT: 'SYSERR_00002',
    MISSING_MANDATORY_FIELD: 'SYSERR_01001',
    // Numeric comparision start
    NUMBER_MUST_BE_POSITIVE: 'SYSERR_01101',
    NUMBER_MUST_BE_NON_NEGATIVE: 'SYSERR_01102',
    NUMBER_MUST_BE_NEGATIVE: 'SYSERR_01103',
    NUMBER_MUST_BE_NON_POSITIVE: 'SYSERR_01104',
    NUMBER_MUST_BE_GREATER_THAN: 'SYSERR_01105',
    NUMBER_MUST_BE_GREATER_EQUAL: 'SYSERR_01106',
    NUMBER_MUST_BE_LESS_THAN: 'SYSERR_01107',
    NUMBER_MUST_BE_LESS_EQUAL: 'SYSERR_01108',
    // Numeric comparision end
    SYSTEM_ERROR: 'SYSERR_09999'
};